#!/bin/bash

brew update;
brew doctor;
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)";
brew install tree;
brew install wget;
brew cask install flux;
brew cask install sourcetree;
brew cask install spectacle;
brew cask install pycharm;
brew cask install google-chrome;
brew cask install google-play-music-desktop-player;
brew install libxml2;
brew install libxslt;
brew install imagemagick ghostscript;
brew install libmemcached;
brew install libxmlsec1;
brew install homebrew/versions/swig304;
brew install pkg-config libffi;
brew install postgresql;
sudo easy_install pip;
pip install virtualenvwrapper;
export WORKON_HOME=~/Envs;
source /usr/local/bin/virtualenvwrapper.sh;
ln -sn ~/personal_projects/dotfiles/gitconfig.symlink ~/.gitconfig;
mv ~/.zshrc ~/.zshrc.bak;
cp ~/personal_projects/dotfiles/robbyrussell-adrienne.zsh-theme ~/.oh-my-zsh/themes/;
ln -sn ~/personal_projects/dotfiles/zshrc.symlink ~/.zshrc;
source ~/.zshrc;
