#!/bin/bash

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)";
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
brew update;
brew doctor;
brew install caskroom/cask/brew-cask;
brew install tree;
brew install git;
brew install wget;
brew cask install virtualbox;
brew cask install vlc;
brew cask install vagrant;
brew cask install iterm2;
brew tap ravenac95/sudolikeaboss;
brew install sudolikeaboss;
brew install hub;
brew cask install github;
brew cask install google-chrome;
brew cask install dropbox;
brew cask install 1password;
brew cask install slack;
brew cask install atom;
brew tap caskroom/fonts;
brew cask install font-inconsolata;
apm stars --user adriennedomingus --install;
brew cask install flux;
brew cask install sourcetree;
brew cask install spectacle;
sudo gem install bundler;
curl -sSL https://get.rvm.io | bash -s stable --ruby;
ln -sn ~/personal_projects/dotfiles/gitconfig.symlink ~/.gitconfig;
mv ~/.zshrc ~/.zshrc.bak;
cp ~/personal_projects/dotfiles/robbyrussell-adrienne.zsh-theme ~/.oh-my-zsh.themes/;
ln -sn ~/personal_projects/dotfiles/zshrc.symlink ~/.zshrc;
source ~/.zshrc;
