#!/bin/bash
brew install wget;
brew cask install iterm2;
brew cask install dropbox;
brew cask install 1password;
brew cask install flux;
brew cask install spectacle;
brew cask install atom;
brew cask install pycharm;
brew cask install google-chrome;
brew cask install google-play-music-desktop-player;
brew install postgresql;
brew install heroku;
brew install gpg;
sudo easy_install pip;
sudo pip install virtualenvwrapper;
ln -sn ~/personal_projects/dotfiles/gitconfig.symlink ~/.gitconfig;
mv ~/.zshrc ~/.zshrc.bak;
ln -sn ~/personal_projects/dotfiles/robbyrussell-adrienne.zsh-theme ~/.oh-my-zsh/themes/;
ln -sn ~/personal_projects/dotfiles/zshrc.symlink ~/.zshrc;
source ~/.zshrc;
touch ~/.hushlogin;
